---
title: "application_plots"
author: "Joe Collins"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = rstudioapi::getActiveProject())


  library(dplyr) # for "glimpse" and data manipulation
  library(ggplot2) # general plotting
  library(ggpubr) # custom plotting
  library(gridExtra) # grid plotting
  library(readxl) # read .xlsx files
  library(readr) # read .txt files
  library(plotrix) # standard error

```

# Data 



```{r data}

getwd()

# ~ read data ####
dat <- read.csv(file = "sym_link_agronomy_data/data/applications_data/normalised_spray_fert_data.csv")


# ~ set factors ####

dat$treatment <- as.factor(dat$treatment)
dat$year <- as.factor(dat$year)
dat$category <- as.factor(dat$category)




# ~ filter the data ####

spray_dat <- filter(.data = dat, activity == "Application" & category != "Fertiliser")

fert_dat <- filter(.data = dat, activity == "Application" & category == "Fertiliser")



# Filter out rows where 'category' is 'Fertiliser'
fert_dat <- fert_dat %>%
  filter(chem_element != "NA")

# set the factor levels
fert_dat$chem_element <- factor(fert_dat$chem_element, levels = c("N","P", "K", "S", "Ca", "Mg", "B", "Cu", "Mn", "Mo", "Zn"))




# ~ expand the df to all combo's

# Create a dataframe with all possible combinations
spray_full_df <- expand.grid(
  treatment = unique(spray_dat$treatment),
  year = unique(spray_dat$year),
  category = unique(spray_dat$category)
)


# Create a dataframe with all possible combinations
fert_full_df <- expand.grid(
  treatment = unique(fert_dat$treatment),
  year = unique(fert_dat$year),
  chem_element = unique(fert_dat$chem_element)
)

```




# Pesticicde sum plots 


```{r pesticide sum plot, echo=FALSE}

# Group by 'treatment' and 'crop' and calculate the sum of 'normalized_rate_kg_ha'
summary_spray_dat_yt <- spray_dat %>%
  group_by(treatment, year, category) %>%
  summarise(Total_Active_Ingredient_kg_ha = sum(normalized_rate_kg_ha, na.rm = TRUE), .groups = 'drop')

# Merge with existing data, filling missing values with 0
summary_spray_dat_yt <- spray_full_df %>%
  left_join(summary_spray_dat_yt, by = c("treatment", "year", "category")) %>%
  mutate(Total_Active_Ingredient_kg_ha = ifelse(is.na(Total_Active_Ingredient_kg_ha), 0, Total_Active_Ingredient_kg_ha))


yt <- 
ggplot(data = summary_spray_dat_yt, 
       aes(x = year, 
           y = Total_Active_Ingredient_kg_ha, 
           group = treatment, 
           fill = treatment)) + 
  geom_bar(stat = "identity", 
           color = "black", 
           position = position_dodge(width = 0.9), 
           width = 0.9) +  
  labs(
    x = "Crop Type",
    y = expression(Total~Active~Ingredient~(kg^{-1}))  
    ) +
  theme_bw() +
  scale_fill_manual(values = c("turquoise3", "tomato2"), 
                    name = "Treatment") +
  theme(
    strip.text.x = element_text(size = 12, 
                                color = "black", 
                                face = "bold.italic"), 
    legend.position = "bottom", 
    axis.title.x = element_blank()
  ) +
  facet_wrap(~ category, 
             ncol = 3, 
             scales = 'free_y') 

yt


```
```{r save pesticide plot}

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/ap_plot_all.png",
       width = 10, height = 5)

```



# pesticide mean plot 


```{r pesticide plot mean}

sum <- 
   spray_dat %>%
  group_by(treatment, year, category) %>%
  summarise(
    n = n(),
    sum1 = round(x = sum(normalized_rate_kg_ha, na.rm = TRUE), digits = 2)
  ) %>% 
  group_by(treatment,category) %>%
  summarise(
    n = n(),
    # sum = round(sum(total_pli_x_rate, na.rm = TRUE), 2),
    mean = mean(sum1, na.rm = TRUE),
    sum2 = sum(sum1),
    sd = sd(sum1, na.rm = TRUE),
    se = sd(sum1, na.rm = TRUE) / sqrt(n) # Standard Error
  )
  
sum


t1 <-
ggplot(data = sum, 
            aes(x = treatment, 
                y = sum2, 
                fill = treatment)) +
geom_bar(stat = "identity", 
           color = "black", 
           position = "dodge") + 
  labs(
    x = "Treatment",
    y = expression(Total~Active~Ingredient~(kg^{-1})) ) +
  theme_bw() +
  scale_fill_manual(values=c("turquoise3","tomato2"), 
                    name = "Treatment") +
      # geom_errorbar(aes(ymin=mean-se,
      #                   ymax=mean+se),
      #               width=.2,                    # Width of the error bars
      #               position=position_dodge(.9)) +
  theme(strip.text.x = element_text(size = 12, 
                                    color = "black", 
                                    face = "bold.italic"), 
        legend.position = "bottom", 
        axis.text.x = element_blank(), 
        axis.title.x = element_blank()) +
  facet_wrap(~ category, 
             ncol = 6, 
             scales = 'free_y') 

t1



```


```{r save pesticide sum plot}

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/pesticide_sum_plot.png",
       width = 10, height = 3.5)

```




# ~ Fertiliser sum plots 


```{r fert plot sum, echo=FALSE}

# Group by 'treatment' and 'crop' and calculate the sum of the chemical element
summary_fert_dat_yt <- fert_dat %>%
  group_by(treatment, year, chem_element) %>%
  summarise(Total_Chem_Element_kg_ha = sum(normalized_rate_kg_ha, na.rm = TRUE), .groups = 'drop')

# Merge with existing data, filling missing values with 0
summary_fert_dat_yt <- fert_full_df %>%
  left_join(summary_fert_dat_yt, by = c("treatment", "year", "chem_element")) %>%
  mutate(Total_Chem_Element_kg_ha = ifelse(is.na(Total_Chem_Element_kg_ha), 0, Total_Chem_Element_kg_ha))


yt <- 
ggplot(data = summary_fert_dat_yt, 
       aes(x = year, 
           y = Total_Chem_Element_kg_ha, 
           group = treatment, 
           fill = treatment)) + 
  geom_bar(stat = "identity", 
           color = "black", 
           position = position_dodge(width = 0.9), 
           width = 0.9) +  
  labs(
    x = "Crop Type",
    y = expression(Chemical~Element~(kg^{-1}))  
    ) +
  theme_bw() +
  scale_fill_manual(values = c("turquoise3", "tomato2"), 
                    name = "Treatment") +
  theme(
    strip.text.x = element_text(size = 12, 
                                color = "black", 
                                face = "bold.italic"), 
    legend.position = "bottom", 
    axis.title.x = element_blank()
  ) +
  facet_wrap(~ chem_element, 
             ncol = 3, 
             scales = 'free_y') 

yt


```

```{r save fert plot}

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/fert_chem_elem_plot.png",
       width = 10, height = 8.5)

```




```{r fert plot mean}

sum <- 
   fert_dat %>%
  group_by(treatment, year, chem_element) %>%
  summarise(
    n = n(),
    sum1 = sum(normalized_rate_kg_ha, na.rm = TRUE)
  ) %>% 
  group_by(treatment,chem_element) %>%
  summarise(
    n = n(),
    # sum = round(sum(total_pli_x_rate, na.rm = TRUE), 2),
    mean = mean(sum1, na.rm = TRUE),
    sum2 = sum(sum1),
    sd = sd(sum1, na.rm = TRUE),
    se = sd(sum1, na.rm = TRUE) / sqrt(n) # Standard Error
  )
  
sum


t1 <-
ggplot(data = sum, 
            aes(x = treatment, 
                y = sum2, 
                fill = treatment)) +
geom_bar(stat = "identity", 
           color = "black", 
           position = "dodge") + 
  labs(
    x = "Treatment",
    y = expression(Chemical~Element~(kg^{-1})) ) +
  theme_bw() +
  scale_fill_manual(values=c("turquoise3","tomato2"), 
                    name = "Treatment") +
      # geom_errorbar(aes(ymin=mean-se,
      #                   ymax=mean+se),
      #               width=.2,                    # Width of the error bars
      #               position=position_dodge(.9)) +
  theme(strip.text.x = element_text(size = 12, 
                                    color = "black", 
                                    face = "bold.italic"), 
        legend.position = "bottom", 
        axis.text.x = element_blank(), 
        axis.title.x = element_blank()) +
  facet_wrap(~ chem_element, 
             ncol = 6, 
             scales = 'free_y') 

t1



```
```{r save fert mean plot}

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/fert_sum_chem_elem_plot.png",
       width = 10, height = 6)

```




#____________________________________
#Pesticide Joint plots


## ~ Herbicide

```{r herbicide}

element_dat <- filter(.data = summary_spray_dat_yt, category == "Herbicide")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


p1 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,1.85) +
      labs(
        x = NULL,
        y = expression(Total~Herbicide~(AI~kg^{-1}~ha^{-1})) ,
        subtitle = expression(Total~Herbicide~(AI~kg^{-1}~ha^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 p2 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,1.85) +
      labs(
        x = NULL,
        y = expression(Mean~Herbicide~(AI~kg^{-1}~ha^{-1})),
        subtitle = expression(Mean~Herbicide~(AI~kg^{-1}~ha^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(p1,p2,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_herbicides.png",
       width = 10, height = 3.5)



```



## ~ Fungicide

```{r Fungicide}

element_dat <- filter(.data = summary_spray_dat_yt, category == "Fungicide")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


p3 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,1.8) +
      labs(
        x = NULL,
        y = expression(Total~Fungicide~(AI~kg^{-1})) ,
        subtitle = expression(Total~Fungicide~(AI~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 p4 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,1.8) +
      labs(
        x = NULL,
        y = expression(Mean~Fungicide~(AI~kg^{-1})),
        subtitle = expression(Mean~Fungicide~(AI~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(p3,p4,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_fungicides.png",
       width = 10, height = 3.5)



```




## ~ Insecticide

```{r Insecticide}

element_dat <- filter(.data = summary_spray_dat_yt, category == "Insecticide")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


p5 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,0.025) +
      labs(
        x = NULL,
        y = expression(Total~Insecticide~(AI~kg^{-1})) ,
        subtitle = expression(Total~Insecticide~(AI~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 p6 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,0.025) +
      labs(
        x = NULL,
        y = expression(Mean~Insecticide~(AI~kg^{-1})),
        subtitle = expression(Mean~Insecticide~(AI~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(p5,p6,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_Insecticide.png",
       width = 10, height = 3.5)



```



## ~ Molluscicide

```{r Molluscicide}

element_dat <- filter(.data = summary_spray_dat_yt, category == "Molluscicide")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


p7 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,0.5) +
      labs(
        x = NULL,
        y = expression(Total~Molluscicide~(AI~kg^{-1})) ,
        subtitle = expression(Total~Molluscicide~(AI~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 p8 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,0.5) +
      labs(
        x = NULL,
        y = expression(Mean~Molluscicide~(AI~kg^{-1})),
        subtitle = expression(Mean~Molluscicide~(AI~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(p7,p8,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_Molluscicide.png",
       width = 10, height = 3.5)



```



## ~ Desiccant

```{r Desiccant}

element_dat <- filter(.data = summary_spray_dat_yt, category == "Desiccant")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


p9 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,1.5) +
      labs(
        x = NULL,
        y = expression(Total~Desiccant~(AI~kg^{-1})) ,
        subtitle = expression(Total~Desiccant~(AI~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 p10 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(0,1.5) +
      labs(
        x = NULL,
        y = expression(Mean~Desiccant~(AI~kg^{-1})),
        subtitle = expression(Mean~Desiccant~(AI~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(p9,p10,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_Desiccant.png",
       width = 10, height = 3.5)



```



## ~ PGR

```{r PGR}

element_dat <- filter(.data = summary_spray_dat_yt, category == "PGR")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


p11 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1,1.8) +
      labs(
        x = NULL,
        y = expression(Total~PGR~(AI~kg^{-1})) ,
        subtitle = expression(Total~PGR~(AI~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Active_Ingredient_kg_ha),
    sd = sd(Total_Active_Ingredient_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 p12 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1,1.8) +
      labs(
        x = NULL,
        y = expression(Mean~PGR~(AI~kg^{-1})),
        subtitle = expression(Mean~PGR~(AI~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(p11,p12,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_PGR.png",
       width = 10, height = 3.5)



```



# large plot


```{r large plot}

ggarrange(p1,p2,p3,p4,p5,p6,
          ncol = 2, nrow = 3,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B", "C", "D", "E", "F"),
          widths = c(2, 1))  # Make first column twice as wide


ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_pesticide_large_plot.png",
       width = 10, height = 9)

```

```{r large plot}

ggarrange(p7,p8,p9,p10,p11,p12,
          ncol = 2, nrow = 3,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B", "C", "D", "E", "F"),
          widths = c(2, 1))  # Make first column twice as wide


ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_plots/fig_minor_pesticides_plot.png",
       width = 10, height = 9)

```






#____________________________________
#Fertiliser Joint plots


## ~ N

```{r N}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "N")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f1 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1,200) +
      labs(
        x = NULL,
        y = expression(Total~Nitrogen~(N~kg^{-1})) ,
        subtitle = expression(Total~Nitrogen~(N~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f2 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1,200) +
      labs(
        x = NULL,
        y = expression(Mean~Nitrogen~(N~kg^{-1})),
        subtitle = expression(Mean~Nitrogen~(N~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f1,f2,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_N.png",
       width = 10, height = 3.5)



```



## ~ P

```{r P}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "P")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f3 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 100) +
      labs(
        x = NULL,
        y = expression(Total~Phosphorus~(P~kg^{-1})) ,
        subtitle = expression(Total~Phosphorus~(P~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f4 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 100) +
      labs(
        x = NULL,
        y = expression(Mean~Phosphorus~(P~kg^{-1})),
        subtitle = expression(Mean~Phosphorus~(P~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f3,f4,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_P.png",
       width = 10, height = 3.5)



```


## ~ K

```{r K}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "K")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f5 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 100) +
      labs(
        x = NULL,
        y = expression(Total~Potassium~(K~kg^{-1})) ,
        subtitle = expression(Total~Potassium~(K~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f6 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 100) +
      labs(
        x = NULL,
        y = expression(Mean~Potassium~(K~kg^{-1})),
        subtitle = expression(Mean~Potassium~(K~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f5,f6,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_K.png",
       width = 10, height = 3.5)



```




## ~ S

```{r S}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "S")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f7 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 130) +
      labs(
        x = NULL,
        y = expression(Total~Sulphur~(S~kg^{-1})) ,
        subtitle = expression(Total~Sulphur~(S~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f8 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 130) +
      labs(
        x = NULL,
        y = expression(Mean~Sulphur~(S~kg^{-1})),
        subtitle = expression(Mean~Sulphur~(S~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f7,f8,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_S.png",
       width = 10, height = 3.5)



```




# large plot


```{r large plot}

ggarrange(f1,f2,f3,f4,f5,f6,f7,f8,
          ncol = 2, nrow = 4,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B", "C", "D", "E", "F","G", "H"),
          widths = c(2, 1))  # Make first column twice as wide


ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_fertiliser_large_plot.png",
       width = 10, height = 12)

```





## ~ Ca

```{r Ca}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "Ca")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f9 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 50) +
      labs(
        x = NULL,
        y = expression(Total~Calcium~(Ca~kg^{-1})) ,
        subtitle = expression(Total~Calcium~(Ca~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f10 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 50) +
      labs(
        x = NULL,
        y = expression(Mean~Calcium~(Ca~kg^{-1})),
        subtitle = expression(Mean~Calcium~(Ca~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f9,f10,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_Ca.png",
       width = 10, height = 3.5)



```


## ~ Mg

```{r Mg}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "Mg")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f11 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 18) +
      labs(
        x = NULL,
        y = expression(Total~Magnesium~(Mg~kg^{-1})) ,
        subtitle = expression(Total~Magnesium~(Mg~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f12 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 18) +
      labs(
        x = NULL,
        y = expression(Mean~Magnesium~(Mg~kg^{-1})),
        subtitle = expression(Mean~Magnesium~(Mg~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f11,f12,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_Mg.png",
       width = 10, height = 3.5)



```



## ~ B

```{r B}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "B")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f13 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 0.4) +
      labs(
        x = NULL,
        y = expression(Total~Boron~(B~kg^{-1})) ,
        subtitle = expression(Total~Boron~(B~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f14 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.1, 0.4) +
      labs(
        x = NULL,
        y = expression(Mean~Boron~(B~kg^{-1})),
        subtitle = expression(Mean~Boron~(B~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f13,f14,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_B.png",
       width = 10, height = 3.5)



```




## ~ Cu

```{r Cu}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "Cu")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f15 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.003, 0.02) +
      labs(
        x = NULL,
        y = expression(Total~Copper~(Cu~kg^{-1})) ,
        subtitle = expression(Total~Copper~(Cu~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f16 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.003, 0.02) +
      labs(
        x = NULL,
        y = expression(Mean~Copper~(Cu~kg^{-1})),
        subtitle = expression(Mean~Copper~(Cu~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f15,f16,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_Cu.png",
       width = 10, height = 3.5)



```


## ~ Mn

```{r Mn}

element_dat <- filter(.data = summary_fert_dat_yt, chem_element == "Mn")

names(element_dat)

# Calculates mean, sd, se and IC - block
summ <- element_dat %>%
  group_by(treatment, year) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))


f17 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.003, 0.4) +
      labs(
        x = NULL,
        y = expression(Total~Manganese~(Mn~kg^{-1})) ,
        subtitle = expression(Total~Manganese~(Mn~kg^{-1})) ,
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      facet_wrap(~ year, 
                 ncol = 4, 
                 scales = 'free_x') 
 

 
 summ <- element_dat %>%
  group_by(treatment) %>%
  summarise( 
    n=n(),
    mean = mean(Total_Chem_Element_kg_ha),
    sd = sd(Total_Chem_Element_kg_ha)
  ) %>%
  mutate( se=sd/sqrt(n))  %>%
  mutate( ic=se * qt((1-0.05)/2 + .5, n-1))
 
 summ$Year <- "All Years"  # Dummy variable for faceting

 
 f18 <-   ggplot(data = summ, 
           aes(x = treatment, 
               y = mean, 
               fill = treatment)) + 
      geom_bar(stat = "identity", 
               color = "black", 
               position = "dodge") + 
   ylim(-0.003, 0.4) +
      labs(
        x = NULL,
        y = expression(Mean~Manganese~(Mn~kg^{-1})),
        subtitle = expression(Mean~Manganese~(Mn~kg^{-1})),
        caption = "") +
      theme_bw() +
      scale_fill_manual(values=c("turquoise3","tomato2"), 
                        name = NULL) +
      theme(strip.text.x = element_text(size = 12, 
                                        color = "black", 
                                        face = "bold.italic"), 
            legend.position = "bottom", 
            # legend.title = element_text(face = "bold")  # <- This line makes the legend title bold
            ) +
      geom_errorbar(aes(ymin = mean - se, 
                        ymax = mean + se),
                    width=.2,                    # Width of the error bars
                    position=position_dodge(.9)) +
      facet_wrap(~Year, ncol = 4)  # Ensure it matches `p1`
 
ggarrange(f17,f18,
          ncol = 2, nrow = 1,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B"),
          widths = c(2, 1))  # Make first column twice as wide

ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_Mn.png",
       width = 10, height = 3.5)



```



# large plot


```{r large plot}

ggarrange(f9,f10,f11,f12,f13,f14,f17,f18,
          ncol = 2, nrow = 4,  
          common.legend = TRUE,  # Use a common legend
          legend = "bottom", 
          labels = c("A", "B", "C", "D", "E", "F","G", "H"),
          widths = c(2, 1))  # Make first column twice as wide


ggsave(filename = "sym_link_agronomy_data/plots/application_plots/new_fert_plots/fig_fertiliser_micronutrients_plot.png",
       width = 10, height = 12)

```